from typing import Optional


class DbNote:
    has_attachment: Optional[int] = None
    unstructure: Optional[str] = None
    title: Optional[str] = None
    content: Optional[str] = None
    html_content: Optional[str] = None
    prefix_uuid: Optional[str] = None
    modified: Optional[int] = None
    tag_id: Optional[str] = None
    extend_fields: Optional[str] = None
    delete_flag: Optional[int] = None
    fold_id: Optional[int] = None
    dirty: Optional[int] = None
    data9: Optional[str] = None
    first_attach_name: Optional[str] = None
    data8: Optional[str] = None
    data7: Optional[str] = None
    data6: Optional[str] = None
    data5: Optional[str] = None
    data4: Optional[str] = None
    created: Optional[int] = None
    data3: Optional[str] = None
    unstruct_uuid: Optional[str] = None
    data2: Optional[str] = None
    data1: Optional[str] = None
    is_lunar: Optional[int] = None
    has_todo: Optional[int] = None
    data10: Optional[str] = None
    guid: Optional[str] = None
    _id: Optional[int] = None
    favorite: Optional[int] = None
    tag_name: Optional[str] = None

    def __init__(self,
                 has_attachment: Optional[int] = None,
                 unstructure: Optional[str] = None,
                 title: Optional[str] = None,
                 content: Optional[str] = None,
                 html_content: Optional[str] = None,
                 prefix_uuid: Optional[str] = None,
                 modified: Optional[int] = None,
                 tag_id: Optional[str] = None,
                 extend_fields: Optional[str] = None,
                 delete_flag: Optional[int] = None,
                 fold_id: Optional[int] = None,
                 dirty: Optional[int] = None,
                 data9: Optional[str] = None,
                 first_attach_name: Optional[str] = None,
                 data8: Optional[str] = None,
                 data7: Optional[str] = None,
                 data6: Optional[str] = None,
                 data5: Optional[str] = None,
                 data4: Optional[str] = None,
                 created: Optional[int] = None,
                 data3: Optional[str] = None,
                 unstruct_uuid: Optional[str] = None,
                 data2: Optional[str] = None,
                 data1: Optional[str] = None,
                 is_lunar: Optional[int] = None,
                 has_todo: Optional[int] = None,
                 data10: Optional[str] = None,
                 guid: Optional[str] = None,
                 _id: Optional[int] = None,
                 favorite: Optional[int] = None,
                 tag_name: Optional[str] = None,
                 ):
        self.has_attachment = has_attachment
        self.unstructure = unstructure
        self.title = title
        self.content = content
        self.html_content = html_content
        self.prefix_uuid = prefix_uuid
        self.modified = modified
        self.tag_id = tag_id
        self.extend_fields = extend_fields
        self.delete_flag = delete_flag
        self.fold_id = fold_id
        self.dirty = dirty
        self.data9 = data9
        self.first_attach_name = first_attach_name
        self.data8 = data8
        self.data7 = data7
        self.data6 = data6
        self.data5 = data5
        self.data4 = data4
        self.created = created
        self.data3 = data3
        self.unstruct_uuid = unstruct_uuid
        self.data2 = data2
        self.data1 = data1
        self.is_lunar = is_lunar
        self.has_todo = has_todo
        self.data10 = data10
        self.guid = guid
        self._id = _id
        self.favorite = favorite
        self.tag_name = tag_name
